### PR TITLE
Update adafruit_ble_radio.py

### PR DESCRIPTION
**Pull request by infamy**
Fix missing timeout param documentation for receive. (present is receive_full but not receive).

### CODE REVIEW

**Comment by infamy** [comment]
Well that's a super cryptic CI failure... any hints? This is just adding a line to improve the docs.

**Comment by tekktrik** [comment]
It looks like `black` is wanting to reformatting one of the files.  You can fix it using `pre-commit` by following the instructions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code  Let me know if I can help with anything!  That should fix the CI error.

**Comment by askpatrickw** [comment]
@infamy do you need any help finishing up this PR?

**Comment by infamy** [comment]
Yeah, i did it directly in github. i dont want to take the time to install
the pre-commit hooks for a minor documentation correction.

Alex

**Review by FoamyGuy — APPROVED** [review]
I ran the formatter and pushed the result to this branch and it's passing now.

This change looks good to me. Thanks for the docs improvement @infamy.

**Pull request merged**
